org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

project.group=com.iamkaf.happyghastimprovements
project.plugins=3.0-SNAPSHOT

mod.name=Happy Ghast Improvements
mod.authors=iamkaf
mod.id=happyghastimprovements
mod.license=MIT
mod.credits=
mod.description=Make happy ghasts faster and quieter.

publish.dry-run=false
publish.curseforge.id=1449981
publish.modrinth.id=OhsFQ3v9
publish.release-type=release
publish.game-versions=auto
dependencies.modrinth.required=amber,konfig
dependencies.curseforge.required=amber-lib,konfig
environments.client=required
environments.server=required

mixin.compat.common=JAVA_18
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_18
mixin.compat.neoforge=JAVA_21
